<?php
defined( 'ABSPATH' ) || exit;
function gmr_theme_defaults():array{return array('gmr_color_ink'=>'#141310','gmr_color_charcoal'=>'#1b1916','gmr_color_paper'=>'#f3efe7','gmr_color_canvas'=>'#faf8f3','gmr_color_accent'=>'#a67b4f','gmr_font_headings'=>'Cormorant Garamond','gmr_font_body'=>'Inter','gmr_home_title'=>'Arte que trasciende la memoria.','gmr_home_description'=>'Un espacio dedicado a preservar, promover y proyectar el legado artístico guatemalteco hacia nuevas generaciones.','gmr_home_intro_kicker'=>'La galería','gmr_home_intro_title'=>'Un proyecto cultural construido desde el arte, la memoria y el legado.','gmr_home_intro_text'=>'Durante más de dos décadas, Galería Mayarí Rojas ha trabajado en la promoción, difusión y valorización del artista, entendiendo cada obra como parte de una historia mayor: la identidad cultural de una nación.','gmr_home_intro_link_label'=>'Conocer la galería','gmr_home_intro_stat_1_value'=>'20+','gmr_home_intro_stat_1_label'=>'años de trayectoria','gmr_home_intro_stat_2_value'=>'Arte','gmr_home_intro_stat_2_label'=>'guatemalteco y contemporáneo','gmr_home_intro_stat_3_value'=>'Legado','gmr_home_intro_stat_3_label'=>'patrimonial y cultural','gmr_footer_kicker'=>'Galería de arte · Guatemala','gmr_footer_title'=>'Arte, memoria y patrimonio.','gmr_collector_label'=>'Coleccionistas');}
function gmr_theme_mod(string $key):string{$defaults=gmr_theme_defaults();return(string)get_theme_mod($key,$defaults[$key]??'');}
function gmr_theme_attachment_ids($value):string{return implode(',',array_values(array_unique(array_filter(array_map('absint',explode(',',(string)$value))))));}
add_action('customize_register',function(WP_Customize_Manager $c):void{
	$c->add_panel('gmr_global',array('title'=>'Mayarí Rojas · Sistema global','priority'=>25,'description'=>'Identidad, colores, tipografías y textos compartidos. El título y descripción general están en Identidad del sitio.'));
	foreach(array('gmr_brand'=>'Logos e identidad','gmr_palette'=>'Paleta de color','gmr_typography'=>'Tipografías','gmr_home_copy'=>'Portada','gmr_global_copy'=>'Textos globales')as$id=>$title)$c->add_section($id,array('title'=>$title,'panel'=>'gmr_global'));
	foreach(array('gmr_logo_dark'=>'Logo oscuro (fondos claros)','gmr_logo_light'=>'Logo claro (fondos oscuros)')as$id=>$label){$c->add_setting($id,array('sanitize_callback'=>'esc_url_raw'));$c->add_control(new WP_Customize_Image_Control($c,$id,array('label'=>$label,'section'=>'gmr_brand')));}
	foreach(array('gmr_color_ink'=>'Texto principal','gmr_color_charcoal'=>'Fondos oscuros','gmr_color_paper'=>'Fondo cálido','gmr_color_canvas'=>'Fondo claro','gmr_color_accent'=>'Color de acento')as$id=>$label){$c->add_setting($id,array('default'=>gmr_theme_defaults()[$id],'sanitize_callback'=>'sanitize_hex_color'));$c->add_control(new WP_Customize_Color_Control($c,$id,array('label'=>$label,'section'=>'gmr_palette')));}
	$fonts=array('Cormorant Garamond'=>'Cormorant Garamond','Playfair Display'=>'Playfair Display','Libre Baskerville'=>'Libre Baskerville','Inter'=>'Inter','Manrope'=>'Manrope','Source Sans 3'=>'Source Sans 3');
	foreach(array('gmr_font_headings'=>'Tipografía de títulos','gmr_font_body'=>'Tipografía de texto')as$id=>$label){$c->add_setting($id,array('default'=>gmr_theme_defaults()[$id],'sanitize_callback'=>static fn($v)=>isset($fonts[$v])?$v:'Inter'));$c->add_control($id,array('label'=>$label,'section'=>'gmr_typography','type'=>'select','choices'=>$fonts));}
	foreach(array('gmr_home_title'=>array('Título principal','gmr_home_copy','text'),'gmr_home_description'=>array('Descripción principal','gmr_home_copy','textarea'),'gmr_footer_kicker'=>array('Antetítulo del pie','gmr_global_copy','text'),'gmr_footer_title'=>array('Mensaje del pie','gmr_global_copy','text'),'gmr_collector_label'=>array('Nombre del área privada','gmr_global_copy','text'))as$id=>$a){$c->add_setting($id,array('default'=>gmr_theme_defaults()[$id],'sanitize_callback'=>'sanitize_text_field'));$c->add_control($id,array('label'=>$a[0],'section'=>$a[1],'type'=>$a[2]));}
	$c->add_setting('gmr_home_hero_images',array('default'=>'','sanitize_callback'=>'gmr_theme_attachment_ids'));
	$c->add_control('gmr_home_hero_images',array('label'=>'IDs de imágenes del hero','description'=>'La galería visual se administra más cómodamente en Apariencia → Opciones Mayarí.','section'=>'gmr_home_copy','type'=>'text'));
	foreach(array('gmr_home_intro_kicker'=>'Antetítulo de presentación','gmr_home_intro_title'=>'Título de presentación','gmr_home_intro_text'=>'Texto de presentación','gmr_home_intro_link_label'=>'Texto del enlace')as$id=>$label){$c->add_setting($id,array('default'=>gmr_theme_defaults()[$id],'sanitize_callback'=>'sanitize_text_field'));$c->add_control($id,array('label'=>$label,'section'=>'gmr_home_copy','type'=>'gmr_home_intro_text'===$id?'textarea':'text'));}
});
function gmr_theme_logo_url(string $variant='dark'):string{$url=get_theme_mod('gmr_logo_'.$variant);if($url)return esc_url_raw($url);if('dark'===$variant){$id=(int)get_theme_mod('custom_logo');if($id&&($logo=wp_get_attachment_image_url($id,'full')))return$logo;}return'light'===$variant?'https://galeriamayarirojas.com/wp-content/uploads/2025/03/mayari-logo-blanco.png':'https://galeriamayarirojas.com/wp-content/uploads/2025/03/mayari-logo-negro.png';}
add_action('wp_enqueue_scripts',function():void{$css=sprintf(':root{--gmr-ink:%1$s;--gmr-charcoal:%2$s;--gmr-paper:%3$s;--gmr-canvas:%4$s;--gmr-bronze:%5$s;--ink:%1$s;--paper:%3$s;--accent:%5$s;--serif:"%6$s",Georgia,serif;--sans:"%7$s","Helvetica Neue",Arial,sans-serif}',esc_attr(gmr_theme_mod('gmr_color_ink')),esc_attr(gmr_theme_mod('gmr_color_charcoal')),esc_attr(gmr_theme_mod('gmr_color_paper')),esc_attr(gmr_theme_mod('gmr_color_canvas')),esc_attr(gmr_theme_mod('gmr_color_accent')),esc_attr(gmr_theme_mod('gmr_font_headings')),esc_attr(gmr_theme_mod('gmr_font_body')));wp_add_inline_style('gmr-design-system',$css);},30);

/* A direct Appearance screen remains usable when a long staging URL breaks WP Customizer integrations. */
add_action('admin_menu',function():void{add_theme_page('Opciones Mayarí Rojas','Opciones Mayarí','edit_theme_options','gmr-theme-options','gmr_theme_options_page');});
add_action('admin_enqueue_scripts',function(string $hook):void{if('appearance_page_gmr-theme-options'===$hook)wp_enqueue_media();});
function gmr_theme_options_page():void{
	if(!current_user_can('edit_theme_options'))return;
	if(isset($_POST['gmr_save'])){check_admin_referer('gmr_theme_options');
		foreach(array('gmr_logo_dark','gmr_logo_light')as$key)set_theme_mod($key,esc_url_raw(wp_unslash($_POST[$key]??'')));
		set_theme_mod('gmr_home_hero_images',gmr_theme_attachment_ids(wp_unslash($_POST['gmr_home_hero_images']??'')));
		set_theme_mod('gmr_home_intro_image',absint($_POST['gmr_home_intro_image']??0));
		foreach(array('gmr_color_ink','gmr_color_charcoal','gmr_color_paper','gmr_color_canvas','gmr_color_accent')as$key){$value=sanitize_hex_color(wp_unslash($_POST[$key]??''));if($value)set_theme_mod($key,$value);}
		$allowed_fonts=array('Cormorant Garamond','Playfair Display','Libre Baskerville','Inter','Manrope','Source Sans 3');foreach(array('gmr_font_headings','gmr_font_body')as$key){$value=sanitize_text_field(wp_unslash($_POST[$key]??''));if(in_array($value,$allowed_fonts,true))set_theme_mod($key,$value);}
		foreach(array('gmr_home_title','gmr_home_description','gmr_home_intro_kicker','gmr_home_intro_title','gmr_home_intro_text','gmr_home_intro_link_label','gmr_home_intro_stat_1_value','gmr_home_intro_stat_1_label','gmr_home_intro_stat_2_value','gmr_home_intro_stat_2_label','gmr_home_intro_stat_3_value','gmr_home_intro_stat_3_label','gmr_footer_kicker','gmr_footer_title','gmr_collector_label')as$key)set_theme_mod($key,sanitize_text_field(wp_unslash($_POST[$key]??'')));
		update_option('blogname',sanitize_text_field(wp_unslash($_POST['blogname']??'')));update_option('blogdescription',sanitize_text_field(wp_unslash($_POST['blogdescription']??'')));update_option('gmr_address',sanitize_text_field(wp_unslash($_POST['gmr_address']??'')));update_option('gmr_public_phone',sanitize_text_field(wp_unslash($_POST['gmr_public_phone']??'')));
		echo'<div class="notice notice-success is-dismissible"><p>Opciones guardadas.</p></div>';
	}
	$fonts=array('Cormorant Garamond','Playfair Display','Libre Baskerville','Inter','Manrope','Source Sans 3');
	$fields=array('gmr_home_title'=>'Título principal de la portada','gmr_home_description'=>'Descripción principal de la portada','gmr_footer_kicker'=>'Antetítulo del pie','gmr_footer_title'=>'Mensaje del pie','gmr_collector_label'=>'Nombre del área privada');
	?><div class="wrap gmr-options"><h1>Opciones globales · Mayarí Rojas</h1><p>Estos valores controlan la identidad visual y los textos compartidos por el tema completo.</p><form method="post"><?php wp_nonce_field('gmr_theme_options');?>
	<style>.gmr-options__grid{display:grid;grid-template-columns:repeat(2,minmax(280px,1fr));gap:20px;max-width:1100px}.gmr-options__card{padding:22px;border:1px solid #dcdcde;background:#fff}.gmr-options__card h2{margin-top:0}.gmr-options label{display:block;margin:16px 0 6px;font-weight:600}.gmr-options input[type=text],.gmr-options input[type=url],.gmr-options textarea,.gmr-options select{width:100%;max-width:none}.gmr-logo-preview{display:block;max-width:240px;max-height:90px;margin:10px 0;padding:10px;background:#ddd}.gmr-hero-preview{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.gmr-hero-preview img{width:100%;aspect-ratio:4/3;object-fit:cover}.gmr-color-row{display:grid;grid-template-columns:1fr 64px;gap:10px;align-items:center}@media(max-width:782px){.gmr-options__grid{grid-template-columns:1fr}}</style>
	<div class="gmr-options__grid"><section class="gmr-options__card"><h2>Identidad del sitio</h2><label for="blogname">Título del sitio</label><input id="blogname" name="blogname" type="text" value="<?php echo esc_attr(get_option('blogname'));?>"><label for="blogdescription">Descripción corta</label><input id="blogdescription" name="blogdescription" type="text" value="<?php echo esc_attr(get_option('blogdescription'));?>"><label for="gmr_address">Dirección pública</label><input id="gmr_address" name="gmr_address" type="text" value="<?php echo esc_attr(get_option('gmr_address'));?>"><label for="gmr_public_phone">Teléfono público</label><input id="gmr_public_phone" name="gmr_public_phone" type="text" value="<?php echo esc_attr(get_option('gmr_public_phone'));?>"></section>
	<section class="gmr-options__card"><h2>Logos institucionales</h2><?php foreach(array('gmr_logo_dark'=>'Logo oscuro · fondos claros','gmr_logo_light'=>'Logo claro · fondos oscuros')as$key=>$label):$url=gmr_theme_logo_url(str_contains($key,'light')?'light':'dark');?><label for="<?php echo esc_attr($key);?>"><?php echo esc_html($label);?></label><input id="<?php echo esc_attr($key);?>" name="<?php echo esc_attr($key);?>" type="url" value="<?php echo esc_attr(get_theme_mod($key));?>" placeholder="<?php echo esc_attr($url);?>"><img class="gmr-logo-preview" data-preview="<?php echo esc_attr($key);?>" src="<?php echo esc_url($url);?>" alt=""><button class="button gmr-media" type="button" data-target="<?php echo esc_attr($key);?>">Elegir de la biblioteca</button><?php endforeach;?></section>
	<section class="gmr-options__card"><h2>Imágenes de portada</h2><p>Selecciona las fotografías en el orden en que deben aparecer. La primera será la imagen inicial.</p><input id="gmr_home_hero_images" name="gmr_home_hero_images" type="hidden" value="<?php echo esc_attr(gmr_theme_attachment_ids(get_theme_mod('gmr_home_hero_images')));?>"><div class="gmr-hero-preview" id="gmr-hero-preview"><?php foreach(array_filter(array_map('absint',explode(',',gmr_theme_attachment_ids(get_theme_mod('gmr_home_hero_images')))))as$image_id):echo wp_get_attachment_image($image_id,'thumbnail');endforeach;?></div><button class="button" id="gmr-select-hero" type="button">Elegir fotografías</button> <button class="button-link-delete" id="gmr-clear-hero" type="button">Vaciar selección</button></section>
	<section class="gmr-options__card"><h2>Presentación de la galería</h2><p>Contenido del segundo bloque de la página principal.</p><?php foreach(array('gmr_home_intro_kicker'=>'Antetítulo','gmr_home_intro_title'=>'Título','gmr_home_intro_text'=>'Párrafo','gmr_home_intro_link_label'=>'Texto del enlace')as$key=>$label):?><label for="<?php echo esc_attr($key);?>"><?php echo esc_html($label);?></label><?php if('gmr_home_intro_text'===$key):?><textarea id="<?php echo esc_attr($key);?>" name="<?php echo esc_attr($key);?>" rows="4"><?php echo esc_textarea(gmr_theme_mod($key));?></textarea><?php else:?><input id="<?php echo esc_attr($key);?>" name="<?php echo esc_attr($key);?>" type="text" value="<?php echo esc_attr(gmr_theme_mod($key));?>"><?php endif;?><?php endforeach;?><h3>Indicadores</h3><?php for($i=1;$i<=3;$i++):?><div style="display:grid;grid-template-columns:1fr 2fr;gap:8px"><input name="gmr_home_intro_stat_<?php echo $i;?>_value" type="text" value="<?php echo esc_attr(gmr_theme_mod('gmr_home_intro_stat_'.$i.'_value'));?>" aria-label="Valor <?php echo $i;?>"><input name="gmr_home_intro_stat_<?php echo $i;?>_label" type="text" value="<?php echo esc_attr(gmr_theme_mod('gmr_home_intro_stat_'.$i.'_label'));?>" aria-label="Descripción <?php echo $i;?>"></div><?php endfor;?><?php $intro_image=absint(get_theme_mod('gmr_home_intro_image'));?><input id="gmr_home_intro_image" name="gmr_home_intro_image" type="hidden" value="<?php echo esc_attr($intro_image);?>"><div class="gmr-hero-preview" id="gmr-intro-preview"><?php if($intro_image)echo wp_get_attachment_image($intro_image,'medium');?></div><button class="button gmr-single-image" type="button" data-input="gmr_home_intro_image" data-preview="gmr-intro-preview">Elegir fotografía</button></section>
	<section class="gmr-options__card"><h2>Paleta global</h2><?php foreach(array('gmr_color_ink'=>'Texto principal','gmr_color_charcoal'=>'Fondos oscuros','gmr_color_paper'=>'Fondo cálido','gmr_color_canvas'=>'Fondo claro','gmr_color_accent'=>'Acento')as$key=>$label):?><label for="<?php echo esc_attr($key);?>"><?php echo esc_html($label);?></label><div class="gmr-color-row"><input id="<?php echo esc_attr($key);?>" name="<?php echo esc_attr($key);?>" type="text" value="<?php echo esc_attr(gmr_theme_mod($key));?>"><input type="color" value="<?php echo esc_attr(gmr_theme_mod($key));?>" data-color="<?php echo esc_attr($key);?>"></div><?php endforeach;?></section>
	<section class="gmr-options__card"><h2>Tipografía</h2><?php foreach(array('gmr_font_headings'=>'Títulos editoriales','gmr_font_body'=>'Texto y navegación')as$key=>$label):?><label for="<?php echo esc_attr($key);?>"><?php echo esc_html($label);?></label><select id="<?php echo esc_attr($key);?>" name="<?php echo esc_attr($key);?>"><?php foreach($fonts as$font):?><option <?php selected(gmr_theme_mod($key),$font);?>><?php echo esc_html($font);?></option><?php endforeach;?></select><?php endforeach;?></section>
	<section class="gmr-options__card"><h2>Textos globales</h2><?php foreach($fields as$key=>$label):?><label for="<?php echo esc_attr($key);?>"><?php echo esc_html($label);?></label><?php if('gmr_home_description'===$key):?><textarea id="<?php echo esc_attr($key);?>" name="<?php echo esc_attr($key);?>" rows="4"><?php echo esc_textarea(gmr_theme_mod($key));?></textarea><?php else:?><input id="<?php echo esc_attr($key);?>" name="<?php echo esc_attr($key);?>" type="text" value="<?php echo esc_attr(gmr_theme_mod($key));?>"><?php endif;?><?php endforeach;?></section></div>
	<p class="submit"><button class="button button-primary" name="gmr_save" value="1">Guardar cambios globales</button></p></form><script>document.querySelectorAll('.gmr-media').forEach(b=>b.onclick=()=>{const frame=wp.media({title:'Seleccionar logo',multiple:false,library:{type:'image'}});frame.on('select',()=>{const a=frame.state().get('selection').first().toJSON();document.getElementById(b.dataset.target).value=a.url;document.querySelector('[data-preview="'+b.dataset.target+'"]').src=a.url});frame.open()});document.querySelectorAll('.gmr-single-image').forEach(b=>b.onclick=()=>{const frame=wp.media({title:'Seleccionar fotografía',button:{text:'Usar esta fotografía'},multiple:false,library:{type:'image'}});frame.on('select',()=>{const a=frame.state().get('selection').first().toJSON();document.getElementById(b.dataset.input).value=a.id;document.getElementById(b.dataset.preview).innerHTML='<img src="'+((a.sizes&&a.sizes.medium)?a.sizes.medium.url:a.url)+'" alt="">'});frame.open()});const heroInput=document.getElementById('gmr_home_hero_images'),heroPreview=document.getElementById('gmr-hero-preview');document.getElementById('gmr-select-hero').onclick=()=>{const frame=wp.media({title:'Imágenes de la portada',button:{text:'Usar en la portada'},multiple:true,library:{type:'image'}});frame.on('open',()=>heroInput.value.split(',').filter(Boolean).forEach(id=>frame.state().get('selection').add(wp.media.attachment(id))));frame.on('select',()=>{const items=frame.state().get('selection').toJSON();heroInput.value=items.map(a=>a.id).join(',');heroPreview.innerHTML=items.map(a=>'<img src="'+((a.sizes&&a.sizes.thumbnail)?a.sizes.thumbnail.url:a.url)+'" alt="">').join('')});frame.open()};document.getElementById('gmr-clear-hero').onclick=()=>{heroInput.value='';heroPreview.innerHTML=''};document.querySelectorAll('[data-color]').forEach(c=>c.oninput=()=>document.getElementById(c.dataset.color).value=c.value);</script></div><?php
}
