<?php
defined( 'ABSPATH' ) || exit;
if ( 'cli' !== PHP_SAPI ) exit( "CLI only\n" );
$term = get_term_by( 'slug', 'elmar-rojas', 'gmr_artist' );
if ( ! $term ) exit( "Elmar term missing\n" );
$biography = '<p>Elmar Rojas fue un artista guatemalteco, arquitecto y figura esencial de la generacion de pintores centroamericanos de los anos sesenta. Su vida profesional reunio la creacion plastica, la arquitectura, la docencia y una participacion activa en la construccion de instituciones culturales.</p><p>Estudio Bellas Artes en la Escuela Nacional de Artes Plasticas de Guatemala y complemento su formacion en la Escuela Pietro Vannucci de Perugia, la Escuela de Artes Decorativas de Paris y la Universidad Complutense de Madrid. Tambien se acerco a la filosofia, la literatura y las ciencias politicas y sociales, disciplinas que ampliaron el horizonte simbolico de su pintura.</p><p>Fue profesor universitario en la Facultad de Arquitectura de la Universidad de San Carlos de Guatemala. Su vinculo con la arquitectura permanecio visible en el rigor compositivo, la construccion del espacio y la monumentalidad de muchas de sus figuras.</p><p>Como gestor cultural impulso numerosos proyectos, participo en la fundacion del Ministerio de Cultura y Deportes de Guatemala y se convirtio en su primer ministro. Entendio la cultura como una responsabilidad publica y como un espacio capaz de conectar educacion, identidad y memoria.</p><p>Su produccion circulo en exposiciones y colecciones de Guatemala, America Latina, Estados Unidos y Europa. Pintura, escultura, obra grafica y joyeria forman parte de un legado que continua dialogando con artistas, criticos, investigadores y nuevas generaciones.</p>';
$history = '<p>La obra de Elmar Rojas es un espacio de relatos y tradiciones populares del pais indigena y mestizo. Campanas, piedras antiguas, filtros de barro, torofuegos, espantapajaros, doncellas y personajes ceremoniales aparecen como rastros de una cultura que el tiempo no ha conseguido borrar.</p><p>Su acercamiento a esas fuentes no sigue el camino de la imitacion ni de la transcripcion literal del folclore. Rojas reconstruye artisticamente ese orden cultural y lo desplaza hacia una realidad plastica contemporanea, sostenida por el dibujo, las veladuras, los colores puros y una intensa conciencia del diseno.</p><p>Durante sus primeras etapas exploro el informalismo y la materia pictorica. Mas tarde desarrollo una cronica social vinculada con la denuncia y la critica politica. En su madurez reformulo esos lenguajes para adentrarse en un mundo personal de signos, personajes y espacios abiertos donde el pasado fluye constantemente sobre el presente.</p><p>La luz de sus pinturas modela paisajes profundos y atmosferas cargadas de misterio. En ellas conviven la serenidad, el asombro y una emocion contenida. La herencia europea y la indigena no aparecen como polos separados, sino entrelazadas en un hilo mestizo que define buena parte de su imaginario.</p><p>Ese universo, frecuentemente relacionado con el realismo magico o lo real maravilloso, no evade la realidad guatemalteca. La transforma para revelar aquello que permanece oculto en la vida cotidiana: la memoria, el mito, la violencia historica, la ternura y la capacidad colectiva de imaginar otros mundos.</p>';
$chronology = '<ol><li><strong>1964–1968</strong><span>Etapa de pintura impasto y exploracion formal.</span></li><li><strong>1968–1972</strong><span>Cronica Social: denuncia y critica frente a la realidad politica.</span></li><li><strong>1975–1980</strong><span>Serie Desnudos Fragmentados.</span></li><li><strong>1980–1984</strong><span>Serie Personajes Conmemorativos.</span></li><li><strong>Desde 1984</strong><span>Desarrollo de la serie Espantapajaros y consolidacion de su imaginario maduro.</span></li><li><strong>2018</strong><span>Fallecimiento de Elmar Rojas; su obra continua como referente del arte guatemalteco.</span></li></ol>';
$awards = '<h3>Premios y reconocimientos</h3><ol><li><strong>1964</strong> Premio Centroamericano de Pintura, Certamen de Cultura, San Salvador.</li><li><strong>1970</strong> Premio Latinoamericano, Casa de la Cultura Ecuatoriana, Quito.</li><li><strong>1978</strong> Primer Premio y Glifo de Oro, I Bienal de Arte Paiz, Guatemala.</li><li><strong>1983</strong> Premio Unico, Bienal Mesoamericana, Museo de Arte Contemporaneo, Panama.</li><li><strong>1984</strong> Gran Premio Iberoamericano Cristobal Colon, Madrid.</li><li><strong>1989</strong> Premio Internacional Camilo Mori, IX Bienal de Arte, Valparaiso.</li><li><strong>1991</strong> Premio Mundial MAAA, reconocido entre quince artistas, Estados Unidos.</li></ol>';
update_term_meta( $term->term_id, 'gmr_artist_biography', $biography );
update_term_meta( $term->term_id, 'gmr_artist_history', $history );
update_term_meta( $term->term_id, 'gmr_artist_chronology', $chronology );
update_term_meta( $term->term_id, 'gmr_artist_awards', $awards );
update_term_meta( $term->term_id, 'gmr_artist_media_ids', '5213,5214' );
delete_term_meta( $term->term_id, 'gmr_artist_document_ids' );
echo wp_json_encode( array( 'term_id' => $term->term_id, 'media' => 2, 'documents' => 1, 'awards' => 7 ) ) . "\n";
