<?php
defined( 'ABSPATH' ) || exit;
if ( 'cli' !== PHP_SAPI ) exit( "CLI only\n" );
$gallery = get_page_by_path( 'la-galeria' );
if ( $gallery ) {
	$content = '<p>Mayari Rojas fundo Galeria Arthis en Guatemala y Galeria Rojas Ford en Miami. Actualmente dirige Galeria Mayari Rojas en Ciudad de Guatemala, preside la Fundacion Elmar Rojas y representa el legado del maestro, incluida la certificacion oficial de su produccion artistica.</p><p>Especialista en arte latinoamericano, ha curado exposiciones, participado en ferias internacionales y acompañado colecciones publicas y privadas. Su trabajo como gestora se orienta a la formacion, promocion y difusion de artistas de Guatemala y America Latina.</p><p>Desde el ano 2000 ha desarrollado proyectos educativos, curatoriales y de intercambio cultural. El rigor con que aborda cada propuesta y su relacion directa con artistas y coleccionistas definen la identidad de la galeria.</p>';
	$history = '<article><strong>2000</strong><p>El Centro Cultural Elmar Rojas abre en zona 15 como espacio de formacion y encuentro. Su proyecto medular fue Galeria Piramide, dirigida por Mayari Rojas.</p></article><article><strong>2006</strong><p>Un incendio obliga al Centro Cultural y a Galeria Piramide a cerrar sus puertas.</p></article><article><strong>2008</strong><p>El proyecto continua como Galeria Arthis en Plaza Fontabella, zona 10, representando oficialmente a Elmar Rojas y promoviendo artistas nacionales y latinoamericanos.</p></article><article><strong>2020</strong><p>Galeria Arthis se transforma en Galeria Mayari Rojas y se traslada a Galerias Tiffany, zona 14, Ciudad de Guatemala.</p></article><article><strong>Hoy</strong><p>La galeria preserva legados, acompana nuevas producciones y crea vinculos entre artistas, instituciones y coleccionistas.</p></article>';
	wp_update_post( array( 'ID'=>$gallery->ID, 'post_content'=>$content, 'post_excerpt'=>'Arte latinoamericano, memoria y gestion cultural desde Ciudad de Guatemala.' ) );
	update_post_meta( $gallery->ID, 'gmr_gallery_history', $history );
}
foreach ( array( 'contacto'=>'Contacto y visita', 'politica-de-privacidad'=>'Politica de privacidad', 'terminos-de-uso'=>'Terminos de uso' ) as $slug=>$title ) {
	$page=get_page_by_path($slug);if(!$page){$id=wp_insert_post(array('post_type'=>'page','post_status'=>'publish','post_title'=>$title,'post_name'=>$slug));$page=get_post($id);}
	if('politica-de-privacidad'===$slug) wp_update_post(array('ID'=>$page->ID,'post_content'=>'<h2>Datos que recopilamos</h2><p>La galeria recibe los datos que usted proporciona al solicitar informacion sobre una obra o al comunicarse directamente: nombre, correo, telefono opcional y mensaje.</p><h2>Finalidad</h2><p>Estos datos se utilizan exclusivamente para responder consultas, preparar citas y mantener la relacion solicitada por el interesado. No se venden datos personales.</p><h2>Acceso privado</h2><p>Las cuentas de Coleccionistas son creadas por la galeria y permiten consultar contenido reservado. La galeria puede desactivar una cuenta cuando corresponda.</p><h2>Conservacion y derechos</h2><p>Las consultas se conservan durante el tiempo necesario para su seguimiento. Puede solicitar acceso, correccion o eliminacion escribiendo al correo publico de la galeria.</p><h2>Proveedores tecnicos</h2><p>El sitio utiliza servicios de alojamiento, correo, seguridad y medicion que pueden procesar datos tecnicos necesarios para operar. Esta politica debera revisarse antes del lanzamiento definitivo.</p>'));
	if('terminos-de-uso'===$slug) wp_update_post(array('ID'=>$page->ID,'post_content'=>'<h2>Catalogo informativo</h2><p>Este sitio funciona como catalogo y no realiza ventas en linea. Disponibilidad, precios y condiciones deben confirmarse directamente con la galeria.</p><h2>Imagenes y contenidos</h2><p>Las imagenes de obras, textos, marcas y documentos estan protegidos por sus respectivos derechos. Su publicacion no concede permiso para reproducirlos o utilizarlos comercialmente.</p><h2>Exactitud</h2><p>La galeria procura mantener la informacion actualizada, pero puede corregir datos curatoriales, disponibilidad y caracteristicas de una obra.</p><h2>Consultas</h2><p>El envio de un formulario no constituye reserva, contrato ni compromiso de venta.</p>'));
}
update_option( 'gmr_address', 'Galerias Tiffany, zona 14, Ciudad de Guatemala' );
echo wp_json_encode(array('gallery'=>$gallery?$gallery->ID:0,'contact'=>get_page_by_path('contacto')->ID,'privacy'=>get_page_by_path('politica-de-privacidad')->ID,'terms'=>get_page_by_path('terminos-de-uso')->ID)) . "\n";
