<?php
defined('ABSPATH')||exit;get_header();
$term=is_tax('product_cat')?get_queried_object():null;$title=$term instanceof WP_Term?$term->name:'Catálogo';$description=$term instanceof WP_Term&&$term->description?$term->description:'Una selección viva de pintura, escultura, obra gráfica y joyería. Cada obra conserva una historia, una procedencia y una mirada propia.';
$artists=get_terms(array('taxonomy'=>'gmr_artist','hide_empty'=>true));$selected_artist=sanitize_title(wp_unslash($_GET['artista']??''));$selected_status=sanitize_key(wp_unslash($_GET['estado']??''));$action=$term instanceof WP_Term?get_term_link($term):get_post_type_archive_link('product');global $wp_query;
?>
<header class="gmr-catalog-hero"><div class="gmr-wrap"><div class="gmr-catalog-hero__top"><span class="gmr-kicker"><?php echo $term?'Disciplina':'Colección Mayarí Rojas';?></span><span class="gmr-catalog-count"><?php echo esc_html((int)$wp_query->found_posts);?> obras</span></div><h1><?php echo esc_html($title);?></h1><div class="gmr-catalog-hero__intro"><p><?php echo esc_html(wp_strip_all_tags($description));?></p><a href="#obras">Explorar selección <span aria-hidden="true">↓</span></a></div></div></header>
<nav class="gmr-catalog-disciplines" aria-label="Disciplinas"><div class="gmr-wrap"><a class="<?php echo !$term?'is-active':'';?>" href="<?php echo esc_url(get_post_type_archive_link('product'));?>">Todo</a><?php foreach(array('pintura'=>'Pintura','escultura'=>'Escultura','obra-grafica'=>'Obra gráfica','joyeria'=>'Joyería','sin-disciplina'=>'Sin disciplina')as$slug=>$label):$category=get_term_by('slug',$slug,'product_cat');if($category):?><a class="<?php echo $term&&$term->slug===$slug?'is-active':'';?>" href="<?php echo esc_url(get_term_link($category));?>"><?php echo esc_html($label);?></a><?php endif;endforeach;?></div></nav>
<section class="gmr-catalog-body" id="obras"><div class="gmr-wrap"><form class="gmr-catalog-tools" method="get" action="<?php echo esc_url($action);?>"><label><span>Artista</span><select name="artista"><option value="">Todos los artistas</option><?php if(!is_wp_error($artists))foreach($artists as$artist)if(gmr_theme_can_view_term($artist->term_id)):?><option value="<?php echo esc_attr($artist->slug);?>" <?php selected($selected_artist,$artist->slug);?>><?php echo esc_html($artist->name);?></option><?php endif;?></select></label><label><span>Disponibilidad</span><select name="estado"><option value="">Todos los estados</option><?php foreach(gmr_theme_commercial_labels()as$key=>$label):?><option value="<?php echo esc_attr($key);?>" <?php selected($selected_status,$key);?>><?php echo esc_html($label);?></option><?php endforeach;?></select></label><button class="gmr-button" type="submit">Aplicar filtros</button><?php if($selected_artist||$selected_status):?><a class="gmr-catalog-clear" href="<?php echo esc_url($action);?>">Limpiar</a><?php endif;?></form>
<?php if(have_posts()):?><div class="gmr-grid gmr-catalog-grid"><?php while(have_posts()){the_post();get_template_part('template-parts/artwork','card');}?></div><nav class="gmr-pagination" aria-label="Paginación"><?php the_posts_pagination(array('mid_size'=>1,'prev_text'=>'←','next_text'=>'→'));?></nav><?php else:?><p class="gmr-empty">No encontramos obras con esta combinación de filtros.</p><?php endif;?></div></section><?php get_footer();?>
