<?php
defined( 'ABSPATH' ) || exit;
$invite = GMR_Core_Collector_Invitations::current();
$state = ( ! $invite || $invite->revoked_at || $invite->used_at || strtotime( $invite->expires_at . ' UTC' ) <= time() ) ? ( ! $invite ? 'invalid' : ( $invite->revoked_at ? 'revoked' : ( $invite->used_at ? 'used' : 'expired' ) ) ) : 'active';
$token = (string) get_query_var( 'gmr_collector_invitation' );
$error = sanitize_key( wp_unslash( $_GET['invite_error'] ?? '' ) );
$messages = array( 'security'=>'La sesión del formulario expiró. Inténtelo de nuevo.', 'details'=>'Revise su nombre, correo y contraseña. La contraseña debe tener al menos 10 caracteres.', 'email_exists'=>'Ya existe una cuenta con este correo. Ingrese desde el acceso de Coleccionistas.', 'create'=>'No pudimos crear la cuenta. Inténtelo nuevamente.' );
get_header(); ?>
<main class="gmr-invite">
	<section class="gmr-invite__intro"><div class="gmr-invite__brand"><img src="<?php echo esc_url( gmr_theme_logo_url( 'light' ) ); ?>" alt="Galería Mayarí Rojas"></div><span class="gmr-kicker">ACCESO PERSONAL · COLECCIONISTAS</span><h1>Una invitación<br>para mirar<br>más cerca.</h1><p>La galería ha reservado este acceso privado para que pueda conocer obras, información y documentación seleccionada.</p><small>Este enlace es personal, de un solo uso y tiene una fecha de vencimiento.</small></section>
	<section class="gmr-invite__panel"><div class="gmr-invite__form"><?php if ( 'active' !== $state ) : ?><span class="gmr-kicker">INVITACIÓN NO DISPONIBLE</span><h2><?php echo esc_html( array( 'used'=>'Este enlace ya fue utilizado.', 'expired'=>'Esta invitación venció.', 'revoked'=>'Esta invitación fue revocada.', 'invalid'=>'Esta invitación no es válida.' )[ $state ] ); ?></h2><p>Para solicitar un nuevo acceso, contacte directamente a Galería Mayarí Rojas.</p><a class="gmr-invite__button" href="<?php echo esc_url( gmr_theme_page_url( 'contacto' ) ); ?>">Contactar a la galería <i>↗</i></a><?php else : ?><span class="gmr-kicker">SU REGISTRO</span><h2>Crear acceso de Coleccionista</h2><p>Complete estos datos para activar su cuenta personal.</p><?php if ( $error && isset( $messages[ $error ] ) ) : ?><div class="gmr-invite__notice" role="alert"><?php echo esc_html( $messages[ $error ] ); ?></div><?php endif; ?><form method="post" action="<?php echo esc_url( GMR_Core_Collector_Invitations::url( $token ) ); ?>"><?php wp_nonce_field( 'gmr_use_collector_invitation_' . $token, 'gmr_invitation_nonce' ); ?><label><span>Nombre completo</span><input name="gmr_invitee_name" type="text" value="<?php echo esc_attr( $invite->invitee_name ); ?>" autocomplete="name" required></label><label><span>Correo electrónico</span><input name="gmr_invitee_email" type="email" value="<?php echo esc_attr( $invite->invitee_email ); ?>" autocomplete="email" <?php echo $invite->invitee_email ? 'readonly' : ''; ?> required></label><label><span>Contraseña</span><input name="gmr_invitee_password" type="password" autocomplete="new-password" minlength="10" required></label><label><span>Confirmar contraseña</span><input name="gmr_invitee_password_confirm" type="password" autocomplete="new-password" minlength="10" required></label><button class="gmr-invite__button" type="submit">Activar mi acceso <i>↗</i></button></form><?php endif; ?></div></section>
</main>
<?php get_footer();
