<?php
defined( 'ABSPATH' ) || exit;
get_header();
$catalog_url=get_post_type_archive_link('product');$events_url=get_post_type_archive_link('gmr_event');$voices_url=get_post_type_archive_link('gmr_tribute');$elmar_url=gmr_theme_page_url('elmar-rojas');$gallery_url=gmr_theme_page_url('la-galeria');$contact_url=gmr_theme_page_url('contacto');
$front_id=(int)get_option('page_on_front');$hero_image=$front_id?get_the_post_thumbnail_url($front_id,'full'):'';$hero_image=$hero_image?:'https://galeriamayarirojas.com/wp-content/uploads/2025/04/portada2gmr.jpg';
$elmar=get_term_by('slug','elmar-rojas','gmr_artist');$elmar_cover=$elmar?absint(get_term_meta($elmar->term_id,'gmr_artist_cover_id',true)):0;$elmar_portrait=$elmar?absint(get_term_meta($elmar->term_id,'gmr_artist_portrait_id',true)):0;
$fallbacks=array('pintura'=>'https://galeriamayarirojas.com/wp-content/uploads/elementor/thumbs/da883ca0-0bcc-47cc-acec-99bdfc6c6910-rq4gswgrr0p58qt4hip8csekfi2t9etopjrodzwe36.jpg','obra-grafica'=>'https://galeriamayarirojas.com/wp-content/uploads/2025/05/obra-grafica.jpg','escultura'=>'https://galeriamayarirojas.com/wp-content/uploads/2025/06/WhatsApp-Image-2025-06-09-at-6.16.10-PM.jpeg','joyeria'=>'https://galeriamayarirojas.com/wp-content/uploads/2025/05/JOYERIA.jpg');
$disciplines=array('pintura'=>array('Pintura','Universos simbólicos'),'obra-grafica'=>array('Obra gráfica','Memoria y trazo'),'escultura'=>array('Escultura','Forma y presencia'),'joyeria'=>array('Joyería','Arte portátil'));
$featured=new WP_Query(array('post_type'=>'product','post_status'=>'publish','posts_per_page'=>3,'meta_key'=>'gmr_featured','meta_value'=>'1','meta_query'=>array(gmr_theme_visibility_meta_query())));if(!$featured->have_posts())$featured=new WP_Query(array('post_type'=>'product','post_status'=>'publish','posts_per_page'=>3,'meta_query'=>array(gmr_theme_visibility_meta_query())));
$events=new WP_Query(array('post_type'=>'gmr_event','post_status'=>'publish','posts_per_page'=>4,'meta_key'=>'gmr_event_start','orderby'=>'meta_value','order'=>'DESC','meta_query'=>array(gmr_theme_visibility_meta_query())));
$voices=new WP_Query(array('post_type'=>'gmr_tribute','post_status'=>'publish','posts_per_page'=>3,'meta_query'=>array(gmr_theme_visibility_meta_query())));
?>
<div class="gmr-home">
<section class="gmr-home-hero"><img class="gmr-home-hero__image" src="<?php echo esc_url($hero_image);?>" alt="Galería Mayarí Rojas"><div class="gmr-home-hero__shade"></div><div class="gmr-wrap gmr-home-hero__content gmr-home-reveal"><span class="gmr-kicker">Galería de arte · Ciudad de Guatemala</span><h1><?php echo esc_html(gmr_theme_mod('gmr_home_title'));?></h1><p><?php echo esc_html(gmr_theme_mod('gmr_home_description'));?></p><div class="gmr-home-actions"><a class="gmr-button gmr-home-button--light" href="<?php echo esc_url($catalog_url);?>">Explorar colección</a><a class="gmr-button gmr-home-button--ghost" href="<?php echo esc_url($contact_url);?>">Visitar la galería</a></div></div><a class="gmr-home-scroll" href="#la-galeria">Descubrir<span></span></a></section>

<section class="gmr-home-section gmr-home-intro" id="la-galeria"><div class="gmr-wrap gmr-home-intro__grid"><div class="gmr-home-intro__copy gmr-home-reveal"><span class="gmr-kicker">La galería</span><h2>Un proyecto cultural construido desde el arte, la memoria y el legado.</h2><p>Durante más de dos décadas, Galería Mayarí Rojas ha trabajado en la promoción, difusión y valorización del artista, entendiendo cada obra como parte de una historia mayor: la identidad cultural de una nación.</p><a class="gmr-home-line-link" href="<?php echo esc_url($gallery_url);?>">Conocer la galería</a><div class="gmr-home-stats"><div><strong>20+</strong><span>años de trayectoria</span></div><div><strong>Arte</strong><span>guatemalteco y contemporáneo</span></div><div><strong>Legado</strong><span>patrimonial y cultural</span></div></div></div><figure class="gmr-home-intro__media gmr-home-reveal"><img src="https://galeriamayarirojas.com/wp-content/uploads/2025/04/h1-video-img-2.jpg" alt="Interior de Galería Mayarí Rojas"></figure></div></section>

<section class="gmr-home-section gmr-home-elmar" id="elmar-rojas"><div class="gmr-wrap"><header class="gmr-home-elmar__head gmr-home-reveal"><span class="gmr-kicker">El legado</span><h2>Elmar Rojas</h2><p>Una obra que dialoga con el realismo mágico, la memoria visual y la sensibilidad profunda de Guatemala.</p></header><div class="gmr-home-disciplines">
<?php foreach($disciplines as $slug=>$copy):$term=get_term_by('slug',$slug,'product_cat');$url=$term?add_query_arg('artista','elmar-rojas',get_term_link($term)):$catalog_url;$image=$fallbacks[$slug];$work=new WP_Query(array('post_type'=>'product','post_status'=>'publish','posts_per_page'=>1,'fields'=>'ids','tax_query'=>array('relation'=>'AND',array('taxonomy'=>'gmr_artist','field'=>'slug','terms'=>'elmar-rojas'),array('taxonomy'=>'product_cat','field'=>'slug','terms'=>$slug)),'meta_query'=>array(gmr_theme_visibility_meta_query())));if($work->posts)$image=get_the_post_thumbnail_url($work->posts[0],'large')?:$image;?>
<a class="gmr-home-discipline gmr-home-reveal" href="<?php echo esc_url($url);?>"><img src="<?php echo esc_url($image);?>" alt="<?php echo esc_attr($copy[0].' de Elmar Rojas');?>"><span class="gmr-home-card-shade"></span><span class="gmr-home-card-copy"><small><?php echo esc_html($copy[0]);?></small><strong><?php echo esc_html($copy[1]);?></strong><em>Ver obras</em></span></a><?php endforeach;wp_reset_postdata();?></div></div></section>

<section class="gmr-home-section gmr-home-catalog" id="coleccion"><div class="gmr-wrap"><header class="gmr-home-section-head gmr-home-reveal"><div><span class="gmr-kicker">Colección</span><h2>Obras, memoria y símbolos para mirar Guatemala desde otra profundidad.</h2></div><a class="gmr-home-line-link" href="<?php echo esc_url($catalog_url);?>">Ver catálogo completo</a></header><div class="gmr-home-bento"><?php $index=0;while($featured->have_posts()):$featured->the_post();$index++;$artist=gmr_theme_term_names(get_the_ID(),'gmr_artist');?><a class="gmr-home-bento__item <?php echo 1===$index?'gmr-home-bento__item--large':'';?> gmr-home-reveal" href="<?php the_permalink();?>"><?php if(has_post_thumbnail())the_post_thumbnail('large');else echo wc_placeholder_img('large');?><span class="gmr-home-card-shade"></span><span class="gmr-home-card-copy"><small><?php echo esc_html($artist?:'Colección Mayarí Rojas');?></small><strong><?php the_title();?></strong><em>Conocer la obra</em></span></a><?php endwhile;wp_reset_postdata();?></div></div></section>

<section class="gmr-home-section gmr-home-memory"><div class="gmr-wrap gmr-home-memory__grid"><div class="gmr-home-memory__copy gmr-home-reveal"><span class="gmr-kicker">Archivo vivo</span><h2>El artista detrás del legado.</h2><p>Fotografías, obras y momentos que permiten acercarse a Elmar Rojas desde su dimensión artística, humana y cultural.</p><a class="gmr-button gmr-home-button--light" href="<?php echo esc_url($elmar_url);?>">Conocer su historia</a></div><div class="gmr-home-memory__images"><figure class="gmr-home-reveal"><?php echo $elmar_cover?wp_get_attachment_image($elmar_cover,'large'):'<img src="https://galeriamayarirojas.com/wp-content/uploads/2025/06/WhatsApp-Image-2025-06-09-at-6.16.11-PM-6.jpeg" alt="Elmar Rojas">';?></figure><figure class="gmr-home-reveal"><?php echo $elmar_portrait?wp_get_attachment_image($elmar_portrait,'large'):'<img src="https://galeriamayarirojas.com/wp-content/uploads/2025/06/WhatsApp-Image-2025-06-09-at-6.15.42-PM-7-1.jpeg" alt="Elmar Rojas en Antigua Guatemala">';?></figure></div></div></section>

<?php if($events->have_posts()):?><section class="gmr-home-section gmr-home-events" id="agenda"><div class="gmr-wrap"><header class="gmr-home-section-head gmr-home-reveal"><div><span class="gmr-kicker">Agenda cultural</span><h2>Encuentros y experiencias para habitar el arte.</h2></div><a class="gmr-home-line-link" href="<?php echo esc_url($events_url);?>">Ver agenda completa</a></header><div class="gmr-home-event-grid"><?php while($events->have_posts()):$events->the_post();?><a class="gmr-home-event gmr-home-reveal" href="<?php the_permalink();?>"><figure><?php if(has_post_thumbnail())the_post_thumbnail('large');?></figure><div><small><?php echo esc_html(gmr_theme_event_date(get_the_ID())?:gmr_theme_event_types(get_the_ID()));?></small><h3><?php the_title();?></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),18));?></p></div></a><?php endwhile;wp_reset_postdata();?></div></div></section><?php endif;?>

<?php if($voices->have_posts()):?><section class="gmr-home-section gmr-home-voices"><div class="gmr-wrap"><header class="gmr-home-section-head gmr-home-reveal"><div><span class="gmr-kicker">Voces sobre Elmar</span><h2>Un legado contado por quienes lo conocieron.</h2></div><a class="gmr-home-line-link" href="<?php echo esc_url($voices_url);?>">Escuchar todas las voces</a></header><div class="gmr-home-voice-grid"><?php while($voices->have_posts()):$voices->the_post();$author=get_post_meta(get_the_ID(),'gmr_tribute_author',true)?:preg_replace('/^Por\s+/u','',get_the_title());?><blockquote class="gmr-home-voice gmr-home-reveal"><a href="<?php the_permalink();?>"><span>“</span><p><?php echo esc_html(wp_trim_words(wp_strip_all_tags(get_the_content()),28));?></p><footer><strong><?php echo esc_html($author);?></strong><small><?php echo esc_html(get_post_meta(get_the_ID(),'gmr_tribute_role',true));?></small></footer></a></blockquote><?php endwhile;wp_reset_postdata();?></div></div></section><?php endif;?>
</div>
<?php get_footer();?>
