<?php
defined( 'ABSPATH' ) || exit;
get_header();
$catalog_url=get_post_type_archive_link('product');$events_url=get_post_type_archive_link('gmr_event');$voices_url=get_post_type_archive_link('gmr_tribute');$elmar_url=gmr_theme_page_url('elmar-rojas');$gallery_url=gmr_theme_page_url('la-galeria');$contact_url=gmr_theme_page_url('contacto');
$front_id=(int)get_option('page_on_front');$hero_image=$front_id?get_the_post_thumbnail_url($front_id,'full'):'';$hero_image=$hero_image?:'https://galeriamayarirojas.com/wp-content/uploads/2025/04/portada2gmr.jpg';$hero_ids=array_values(array_filter(array_map('absint',explode(',',gmr_theme_attachment_ids(get_theme_mod('gmr_home_hero_images'))))));
$elmar=get_term_by('slug','elmar-rojas','gmr_artist');$elmar_cover=$elmar?absint(get_term_meta($elmar->term_id,'gmr_artist_cover_id',true)):0;$elmar_portrait=$elmar?absint(get_term_meta($elmar->term_id,'gmr_artist_portrait_id',true)):0;$home_elmar_image=absint(get_theme_mod('gmr_home_elmar_image'))?:$elmar_cover;
$fallbacks=array('pintura'=>'https://galeriamayarirojas.com/wp-content/uploads/elementor/thumbs/da883ca0-0bcc-47cc-acec-99bdfc6c6910-rq4gswgrr0p58qt4hip8csekfi2t9etopjrodzwe36.jpg','obra-grafica'=>'https://galeriamayarirojas.com/wp-content/uploads/2025/05/obra-grafica.jpg','escultura'=>'https://galeriamayarirojas.com/wp-content/uploads/2025/06/WhatsApp-Image-2025-06-09-at-6.16.10-PM.jpeg','joyeria'=>'https://galeriamayarirojas.com/wp-content/uploads/2025/05/JOYERIA.jpg');
$disciplines=array('pintura'=>array('Pintura','Universos simbólicos'),'obra-grafica'=>array('Obra gráfica','Memoria y trazo'),'escultura'=>array('Escultura','Forma y presencia'),'joyeria'=>array('Joyería','Arte portátil'));
$eligible=array('post_type'=>'product','post_status'=>'publish','fields'=>'ids','orderby'=>'date','order'=>'DESC','meta_query'=>array(gmr_theme_public_visibility_meta_query(),array('key'=>'_thumbnail_id','compare'=>'EXISTS')));$featured_ids=get_posts(array_merge($eligible,array('posts_per_page'=>-1,'meta_query'=>array(gmr_theme_public_visibility_meta_query(),array('key'=>'_thumbnail_id','compare'=>'EXISTS'),array('key'=>'gmr_featured','value'=>'1')))));if(count($featured_ids)<3){$fill=get_posts(array_merge($eligible,array('posts_per_page'=>3-count($featured_ids),'post__not_in'=>$featured_ids)));$featured_ids=array_values(array_unique(array_merge($featured_ids,$fill)));}$featured_groups=$featured_ids?array_chunk($featured_ids,3):array();if(count($featured_groups)>1&&count(end($featured_groups))<3){$last=array_pop($featured_groups);$needed=3-count($last);$featured_groups[]=array_merge($last,array_slice($featured_ids,0,$needed));}
$events=new WP_Query(array('post_type'=>'gmr_event','post_status'=>'publish','posts_per_page'=>4,'meta_key'=>'gmr_event_start','orderby'=>'meta_value','order'=>'DESC','meta_query'=>array(gmr_theme_visibility_meta_query())));
$voice_posts=get_posts(array('post_type'=>'gmr_tribute','post_status'=>'publish','posts_per_page'=>-1,'orderby'=>'date','order'=>'DESC','meta_query'=>array(gmr_theme_public_visibility_meta_query())));usort($voice_posts,static fn($a,$b)=>(int)(bool)get_post_meta($b->ID,'gmr_tribute_featured',true)<=>(int)(bool)get_post_meta($a->ID,'gmr_tribute_featured',true));$voice_groups=$voice_posts?array_chunk($voice_posts,3):array();if(count($voice_groups)>1&&count(end($voice_groups))<3){$last=array_pop($voice_groups);$voice_groups[]=array_merge($last,array_slice($voice_posts,0,3-count($last)));}
?>
<div class="gmr-home">
<section class="gmr-home-hero" data-hero-slider><div class="gmr-home-hero__slides"><?php if($hero_ids):foreach($hero_ids as$i=>$image_id):?><figure class="gmr-home-hero__slide<?php echo 0===$i?' is-active':'';?>" aria-hidden="<?php echo 0===$i?'false':'true';?>"><?php echo wp_get_attachment_image($image_id,'full',false,array('alt'=>'Interior de Galería Mayarí Rojas','loading'=>0===$i?'eager':'lazy','fetchpriority'=>0===$i?'high':'auto'));?></figure><?php endforeach;else:?><figure class="gmr-home-hero__slide is-active" aria-hidden="false"><img src="<?php echo esc_url($hero_image);?>" alt="Galería Mayarí Rojas" loading="eager" fetchpriority="high"></figure><?php endif;?></div><div class="gmr-home-hero__shade"></div><div class="gmr-wrap gmr-home-hero__content gmr-home-reveal"><span class="gmr-kicker">Galería de arte · Ciudad de Guatemala</span><h1><?php echo esc_html(gmr_theme_mod('gmr_home_title'));?></h1><p><?php echo esc_html(gmr_theme_mod('gmr_home_description'));?></p><div class="gmr-home-actions"><a class="gmr-button gmr-home-button--light" href="<?php echo esc_url($catalog_url);?>">Explorar colección</a><a class="gmr-button gmr-home-button--ghost" href="<?php echo esc_url($contact_url);?>">Visitar la galería</a></div></div><a class="gmr-home-scroll" href="#la-galeria">Descubrir<span></span></a></section>

<?php $intro_image=absint(get_theme_mod('gmr_home_intro_image'));?><section class="gmr-home-section gmr-home-intro" id="la-galeria"><div class="gmr-wrap gmr-home-intro__grid"><div class="gmr-home-intro__copy gmr-home-reveal"><span class="gmr-kicker"><?php echo esc_html(gmr_theme_mod('gmr_home_intro_kicker'));?></span><h2><?php echo esc_html(gmr_theme_mod('gmr_home_intro_title'));?></h2><p><?php echo esc_html(gmr_theme_mod('gmr_home_intro_text'));?></p><a class="gmr-home-line-link" href="<?php echo esc_url($gallery_url);?>"><?php echo esc_html(gmr_theme_mod('gmr_home_intro_link_label'));?></a><div class="gmr-home-stats"><?php for($i=1;$i<=3;$i++):?><div><strong><?php echo esc_html(gmr_theme_mod('gmr_home_intro_stat_'.$i.'_value'));?></strong><span><?php echo esc_html(gmr_theme_mod('gmr_home_intro_stat_'.$i.'_label'));?></span></div><?php endfor;?></div></div><figure class="gmr-home-intro__media gmr-home-reveal"><?php echo $intro_image?wp_get_attachment_image($intro_image,'full',false,array('alt'=>'Visitantes en Galería Mayarí Rojas')):'<img src="https://galeriamayarirojas.com/wp-content/uploads/2025/04/h1-video-img-2.jpg" alt="Interior de Galería Mayarí Rojas">';?></figure></div></section>

<section class="gmr-home-section gmr-home-elmar" id="elmar-rojas"><div class="gmr-wrap"><header class="gmr-home-elmar__head gmr-home-reveal"><span class="gmr-kicker">El legado</span><h2>Elmar Rojas</h2><p>Una obra que dialoga con el realismo mágico, la memoria visual y la sensibilidad profunda de Guatemala.</p></header><div class="gmr-home-disciplines">
<?php foreach($disciplines as $slug=>$copy):$term=get_term_by('slug',$slug,'product_cat');$url=$term?add_query_arg('artista','elmar-rojas',get_term_link($term)):$catalog_url;$image=gmr_theme_elmar_discipline_image($slug)?:$fallbacks[$slug];?>
<a class="gmr-home-discipline gmr-home-reveal" href="<?php echo esc_url($url);?>"><img src="<?php echo esc_url($image);?>" alt="<?php echo esc_attr($copy[0].' de Elmar Rojas');?>"><span class="gmr-home-card-shade"></span><span class="gmr-home-card-copy"><small><?php echo esc_html($copy[0]);?></small><strong><?php echo esc_html($copy[1]);?></strong><em>Ver obras</em></span></a><?php endforeach;wp_reset_postdata();?></div></div></section>

<section class="gmr-home-section gmr-home-catalog" id="coleccion"><div class="gmr-wrap"><header class="gmr-home-section-head gmr-home-reveal"><div><span class="gmr-kicker">Colección</span><h2>Obras, memoria y símbolos para mirar Guatemala desde otra profundidad.</h2></div><a class="gmr-home-line-link" href="<?php echo esc_url($catalog_url);?>">Ver catálogo completo</a></header><?php if($featured_groups):?><div class="gmr-home-bento-rotator" data-artwork-rotator><?php foreach($featured_groups as$group_index=>$group):?><div class="gmr-home-bento<?php echo 0===$group_index?' is-active':'';?>" aria-hidden="<?php echo 0===$group_index?'false':'true';?>"><?php foreach($group as$index=>$product_id):$GLOBALS['post']=get_post($product_id);setup_postdata($GLOBALS['post']);$artist=gmr_theme_term_names($product_id,'gmr_artist');?><a class="gmr-home-bento__item <?php echo 0===$index?'gmr-home-bento__item--large':'';?> gmr-home-reveal" href="<?php the_permalink();?>"><?php the_post_thumbnail('large');?><span class="gmr-home-card-shade"></span><span class="gmr-home-card-copy"><small><?php echo esc_html($artist?:'Colección Mayarí Rojas');?></small><strong><?php the_title();?></strong><em>Conocer la obra</em></span></a><?php endforeach;wp_reset_postdata();?></div><?php endforeach;?></div><?php endif;?></div></section>

<section class="gmr-home-section gmr-home-memory"><div class="gmr-wrap gmr-home-memory__grid"><div class="gmr-home-memory__copy gmr-home-reveal"><span class="gmr-kicker">Archivo vivo</span><h2>El artista detrás del legado.</h2><p>Fotografías, obras y momentos que permiten acercarse a Elmar Rojas desde su dimensión artística, humana y cultural.</p><a class="gmr-button gmr-home-button--light" href="<?php echo esc_url($elmar_url);?>">Conocer su historia</a></div><div class="gmr-home-memory__images"><figure class="gmr-home-reveal"><?php echo $home_elmar_image?wp_get_attachment_image($home_elmar_image,'large',false,array('alt'=>'Elmar Rojas trabajando sobre una obra gráfica')):'<img src="https://galeriamayarirojas.com/wp-content/uploads/2025/06/WhatsApp-Image-2025-06-09-at-6.16.11-PM-6.jpeg" alt="Elmar Rojas">';?></figure><figure class="gmr-home-reveal"><?php echo $elmar_portrait?wp_get_attachment_image($elmar_portrait,'large'):'<img src="https://galeriamayarirojas.com/wp-content/uploads/2025/06/WhatsApp-Image-2025-06-09-at-6.15.42-PM-7-1.jpeg" alt="Elmar Rojas en Antigua Guatemala">';?></figure></div></div></section>

<?php if($events->have_posts()):?><section class="gmr-home-section gmr-home-events" id="agenda"><div class="gmr-wrap"><header class="gmr-home-section-head gmr-home-reveal"><div><span class="gmr-kicker">Agenda cultural</span><h2>Encuentros y experiencias para habitar el arte.</h2></div><a class="gmr-home-line-link" href="<?php echo esc_url($events_url);?>">Ver agenda completa</a></header><div class="gmr-home-event-grid"><?php while($events->have_posts()):$events->the_post();?><a class="gmr-home-event gmr-home-reveal" href="<?php the_permalink();?>"><figure><?php if(has_post_thumbnail())the_post_thumbnail('large');?></figure><div><small><?php echo esc_html(gmr_theme_event_date(get_the_ID())?:gmr_theme_event_types(get_the_ID()));?></small><h3><?php the_title();?></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),18));?></p></div></a><?php endwhile;wp_reset_postdata();?></div></div></section><?php endif;?>

<?php if($voice_groups):?><section class="gmr-home-section gmr-home-voices"><div class="gmr-wrap"><header class="gmr-home-section-head gmr-home-reveal"><div><span class="gmr-kicker">Voces sobre Elmar</span><h2>Un legado contado por quienes lo conocieron.</h2></div><a class="gmr-home-line-link" href="<?php echo esc_url($voices_url);?>">Escuchar todas las voces</a></header><div class="gmr-home-voice-rotator" data-voice-rotator><?php foreach($voice_groups as$group_index=>$group):?><div class="gmr-home-voice-grid<?php echo 0===$group_index?' is-active':'';?>" data-voice-group="<?php echo esc_attr($group_index);?>" aria-hidden="<?php echo 0===$group_index?'false':'true';?>"><?php foreach($group as$voice):$author=get_post_meta($voice->ID,'gmr_tribute_author',true)?:preg_replace('/^Por\s+/u','',$voice->post_title);?><blockquote class="gmr-home-voice"><a href="<?php echo esc_url(get_permalink($voice));?>"<?php echo 0===$group_index?'':' tabindex="-1"';?>><span>“</span><p><?php echo esc_html(wp_trim_words(wp_strip_all_tags($voice->post_content),28));?></p><footer><strong><?php echo esc_html($author);?></strong><small><?php echo esc_html(get_post_meta($voice->ID,'gmr_tribute_role',true));?></small></footer></a></blockquote><?php endforeach;?></div><?php endforeach;?></div></div></section><?php endif;?>
</div>
<?php get_footer();?>
