<?php
get_header();
$elmar = get_term_by( 'slug', 'elmar-rojas', 'gmr_artist' );
$term_id = $elmar ? $elmar->term_id : 0;
$portrait = absint( get_term_meta( $term_id, 'gmr_artist_portrait_id', true ) );
$cover = absint( get_term_meta( $term_id, 'gmr_artist_cover_id', true ) );
$biography = get_term_meta( $term_id, 'gmr_artist_biography', true );
$history = get_term_meta( $term_id, 'gmr_artist_history', true );
$chronology = get_term_meta( $term_id, 'gmr_artist_chronology', true );
$awards = get_term_meta( $term_id, 'gmr_artist_awards', true );
$media_ids = array_filter( array_map( 'absint', explode( ',', get_term_meta( $term_id, 'gmr_artist_media_ids', true ) ) ) );
$documents = class_exists( 'GMR_Core_Documents' ) && current_user_can( 'gmr_download_collector_documents' ) ? GMR_Core_Documents::get_documents( 'artist', $term_id ) : array();
$photo_archives = new WP_Query( array(
	'post_type'      => 'gmr_media_gallery',
	'post_status'    => 'publish',
	'posts_per_page' => 3,
	'tax_query'      => array( array( 'taxonomy' => 'gmr_artist', 'field' => 'term_id', 'terms' => $term_id ) ),
	'meta_query'     => array( gmr_theme_visibility_meta_query() ),
) );
?>
<nav class="gmr-elmar-index" aria-label="Contenido de Elmar Rojas"><div class="gmr-wrap"><a href="#biografia">Biografia</a><a href="#cronologia">Cronologia</a><a href="#disciplinas">Disciplinas</a><a href="#voces">Voces</a><a href="#archivo">Archivo</a><a href="#obra-elmar">Obra</a></div></nav>
<section class="gmr-elmar-hero"><div class="gmr-elmar-hero__art"><?php echo wp_get_attachment_image( $cover ?: $portrait, 'full' ); ?></div><div class="gmr-wrap gmr-elmar-hero__content"><span class="gmr-kicker">Artista principal · Guatemala</span><h1>Elmar<br>Rojas</h1><p>Pintor, arquitecto y figura esencial del arte guatemalteco.</p><a class="gmr-button" href="#obra-elmar">Explorar su obra</a></div></section>
<section class="gmr-section" id="biografia"><div class="gmr-wrap gmr-elmar-text"><div><span class="gmr-kicker">Biografia</span><h2>Una vida entre arte, cultura y memoria</h2></div><div class="gmr-editorial"><?php echo wp_kses_post( wpautop( $biography ) ); ?></div></div></section>
<?php if ( $history ) : ?><section class="gmr-section gmr-section--white"><div class="gmr-wrap gmr-elmar-text"><div><span class="gmr-kicker">Trayectoria</span><h2>El mundo de Elmar Rojas</h2></div><div class="gmr-editorial"><?php echo wp_kses_post( wpautop( $history ) ); ?></div></div></section><?php endif; ?>
<?php if ( $chronology ) : ?><section class="gmr-section" id="cronologia"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">Cronologia artistica</span><h2>Etapas de una obra</h2></div></div><div class="gmr-timeline"><?php echo wp_kses_post( $chronology ); ?></div></div></section><?php endif; ?>
<section class="gmr-section gmr-section--dark" id="disciplinas"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">El legado</span><h2>Cuatro disciplinas</h2></div></div><div class="gmr-discipline-grid"><?php foreach(array('pintura'=>'Pintura','escultura'=>'Escultura','obra-grafica'=>'Obra gráfica','joyeria'=>'Joyería')as$slug=>$label):$term=get_term_by('slug',$slug,'product_cat');?><a href="<?php echo esc_url($term?add_query_arg('artista','elmar-rojas',get_term_link($term)):'#');?>"><img src="<?php echo esc_url(gmr_theme_elmar_discipline_image($slug));?>" alt="<?php echo esc_attr($label.' de Elmar Rojas');?>"><i aria-hidden="true"></i><span>Explorar</span><strong><?php echo esc_html($label);?></strong></a><?php endforeach;?></div></div></section>
<?php $voices=new WP_Query(array('post_type'=>'gmr_tribute','post_status'=>'publish','posts_per_page'=>3,'orderby'=>'date','order'=>'DESC','meta_query'=>array(gmr_theme_visibility_meta_query())));if($voices->have_posts()):?><section class="gmr-section" id="voces"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">Voces sobre Elmar</span><h2>Miradas sobre su legado</h2></div><a class="gmr-button" href="<?php echo esc_url(get_post_type_archive_link('gmr_tribute'));?>">Ver todas</a></div><div class="gmr-voice-grid"><?php while($voices->have_posts()):$voices->the_post();$author=get_post_meta(get_the_ID(),'gmr_tribute_author',true)?:preg_replace('/^Por\s+/u','',get_the_title());$role=get_post_meta(get_the_ID(),'gmr_tribute_role',true);$date=get_post_meta(get_the_ID(),'gmr_tribute_date',true);$excerpt=has_excerpt()?get_the_excerpt():wp_trim_words(wp_strip_all_tags(get_the_content()),24);?><blockquote class="gmr-voice-card"><a href="<?php the_permalink();?>"><div class="gmr-voice-card__quote"><?php echo esc_html($excerpt);?></div><footer><strong><?php echo esc_html($author);?></strong><?php if($role):?><span><?php echo esc_html($role);?></span><?php endif;?><?php if($date):?><time><?php echo esc_html($date);?></time><?php endif;?></footer></a></blockquote><?php endwhile;wp_reset_postdata();?></div></div></section><?php endif;?>
<?php if ( $awards || $documents || $media_ids || $photo_archives->have_posts() ) : ?><section class="gmr-section gmr-section--white" id="archivo"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">Patrimonio documental</span><h2>Archivo y publicaciones</h2></div></div><?php if($awards):?><div class="gmr-editorial"><?php echo wp_kses_post(wpautop($awards));?></div><?php endif; ?><?php if($documents):?><div class="gmr-document-grid"><?php foreach($documents as $document):?><a class="gmr-document" href="<?php echo esc_url(GMR_Core_Documents::url($document->ID));?>"><span>Documento reservado</span><strong><?php echo esc_html($document->post_title);?></strong><small>Descargar</small></a><?php endforeach;?></div><?php endif;?><?php if($media_ids):?><div class="gmr-elmar-media"><?php foreach($media_ids as $image_id) echo wp_get_attachment_image($image_id,'large');?></div><?php endif;?><?php if($photo_archives->have_posts()):?><div class="gmr-elmar-photo-archives"><div class="gmr-section__head"><div><span class="gmr-kicker">Archivo fotográfico</span><h3>Elmar Rojas: vida y obra</h3></div><a class="gmr-button" href="<?php echo esc_url(get_post_type_archive_link('gmr_media_gallery'));?>">Ver archivo multimedia</a></div><div class="gmr-media-bento"><?php $archive_index=0;while($photo_archives->have_posts()):$photo_archives->the_post();get_template_part('template-parts/media','card',array('index'=>$archive_index++));endwhile;wp_reset_postdata();?></div></div><?php endif;?></div></section><?php endif;?>
<?php $works=new WP_Query(array('post_type'=>'product','post_status'=>'publish','posts_per_page'=>9,'tax_query'=>array(array('taxonomy'=>'gmr_artist','field'=>'slug','terms'=>'elmar-rojas')),'meta_query'=>array(gmr_theme_visibility_meta_query())));?><section class="gmr-section" id="obra-elmar"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">Catalogo</span><h2>Obras de Elmar Rojas</h2></div></div><div class="gmr-grid"><?php while($works->have_posts()){$works->the_post();get_template_part('template-parts/artwork','card');}wp_reset_postdata();?></div></div></section>
<?php get_footer(); ?>
