<?php
defined('ABSPATH')||exit;get_header();while(have_posts()):the_post();$id=get_the_ID();$product=wc_get_product($id);$artist_terms=wp_get_post_terms($id,'gmr_artist');$artist=!is_wp_error($artist_terms)&&$artist_terms?$artist_terms[0]:null;$artist_name=$artist?$artist->name:'Artista anónimo';$status=get_post_meta($id,'gmr_commercial_status',true)?:'available';$image_ids=array_values(array_unique(array_filter(array_merge(array(get_post_thumbnail_id($id)),$product?$product->get_gallery_image_ids():array()))));
$facts=array('Año'=>gmr_theme_year($id),'Técnica'=>gmr_theme_term_names($id,'gmr_technique'),'Soporte'=>gmr_theme_term_names($id,'gmr_support'),'Materiales'=>gmr_theme_term_names($id,'gmr_material'),'Medidas'=>gmr_theme_dimensions($id),'Colección'=>gmr_theme_term_names($id,'gmr_collection'),'Edición'=>gmr_theme_edition_label($id),'Firma'=>gmr_theme_signature_label($id),'Certificado'=>gmr_theme_certificate_label($id));
?>
<nav class="gmr-artwork-breadcrumb"><div class="gmr-wrap"><a href="<?php echo esc_url(get_post_type_archive_link('product'));?>">Catálogo</a><span>/</span><?php $cats=wp_get_post_terms($id,'product_cat');if(!is_wp_error($cats)&&$cats):?><a href="<?php echo esc_url(get_term_link($cats[0]));?>"><?php echo esc_html($cats[0]->name);?></a><span>/</span><?php endif;?><span><?php the_title();?></span></div></nav>
<article class="gmr-artwork"><div class="gmr-wrap gmr-artwork__layout"><div class="gmr-artwork__gallery"><?php if($image_ids):foreach($image_ids as$i=>$image_id):?><figure class="<?php echo 0===$i?'gmr-artwork__image--primary':'';?>"><?php echo wp_get_attachment_image($image_id,'full',false,array('loading'=>0===$i?'eager':'lazy'));?></figure><?php endforeach;else:?><figure><?php echo wc_placeholder_img('full');?></figure><?php endif;?></div>
<aside class="gmr-artwork__info"><div class="gmr-artwork__eyebrow"><span class="gmr-kicker">Obra</span><span class="gmr-card__status gmr-card__status--<?php echo esc_attr($status);?>"><?php echo esc_html(gmr_theme_commercial_label($status));?></span></div><div class="gmr-artwork__artist"><?php if($artist):?><a href="<?php echo esc_url(get_term_link($artist));?>"><?php echo esc_html($artist_name);?> <span aria-hidden="true">↗</span></a><?php else:echo esc_html($artist_name);endif;?></div><h1><?php the_title();?></h1><?php if($product&&$product->get_sku()):?><div class="gmr-artwork__sku">Referencia <?php echo esc_html($product->get_sku());?></div><?php endif;?>
<dl class="gmr-facts"><?php foreach($facts as$label=>$value)if($value):?><div class="gmr-fact"><dt><?php echo esc_html($label);?></dt><dd><?php echo esc_html($value);?></dd></div><?php endif;?></dl>
<div class="gmr-artwork__commercial"><?php if(gmr_theme_can_view_price($id)):?><span>Precio</span><div class="gmr-price"><?php echo $product&&$product->get_price()?wp_kses_post($product->get_price_html()):esc_html(get_post_meta($id,'gmr_price_label',true)?:'Consultar');?></div><?php else:?><span>Información comercial</span><p>Precio disponible para coleccionistas autorizados o mediante consulta privada.</p><?php endif;?><a class="gmr-button" href="#consultar">Consultar esta obra</a></div>
<?php if(get_the_content()):?><div class="gmr-artwork__description"><span class="gmr-kicker">Sobre la obra</span><div class="gmr-editorial"><?php the_content();?></div></div><?php endif;?></aside></div></article>
<?php echo do_shortcode('[gmr_artwork_inquiry product_id="'.$id.'"]'); ?>
<?php if(class_exists('GMR_Core_Documents')&&current_user_can('gmr_download_collector_documents')):$documents=GMR_Core_Documents::get_documents('product',$id);if($documents):?><section class="gmr-section gmr-section--white"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">Documentación reservada</span><h2>Ficha y certificados</h2></div></div><div class="gmr-document-grid"><?php foreach($documents as$document):?><a class="gmr-document" href="<?php echo esc_url(GMR_Core_Documents::url($document->ID));?>"><span>Documento privado</span><strong><?php echo esc_html($document->post_title);?></strong><small>Descargar</small></a><?php endforeach;?></div></div></section><?php endif;endif;?>
<?php $related_args=array('post_type'=>'product','post_status'=>'publish','post__not_in'=>array($id),'posts_per_page'=>3,'meta_query'=>array(gmr_theme_visibility_meta_query()));if($artist)$related_args['tax_query']=array(array('taxonomy'=>'gmr_artist','field'=>'term_id','terms'=>$artist->term_id));$related=new WP_Query($related_args);if($related->have_posts()):?><section class="gmr-section gmr-artwork-related"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">Continuar explorando</span><h2>Más obras<?php echo $artist?' de '.esc_html($artist_name):'';?></h2></div><a class="gmr-home-line-link" href="<?php echo esc_url($artist?get_term_link($artist):get_post_type_archive_link('product'));?>">Ver selección completa</a></div><div class="gmr-grid"><?php while($related->have_posts()){$related->the_post();get_template_part('template-parts/artwork','card');}wp_reset_postdata();?></div></div></section><?php endif;?>
<?php endwhile;get_footer();?>
