<?php
defined('ABSPATH')||exit;$term=get_queried_object();if('elmar-rojas'===$term->slug||'elmar'===get_term_meta($term->term_id,'gmr_artist_special_template',true)){wp_safe_redirect(gmr_theme_page_url('elmar-rojas'),301);exit;}get_header();$portrait=absint(get_term_meta($term->term_id,'gmr_artist_portrait_id',true));$cover=absint(get_term_meta($term->term_id,'gmr_artist_cover_id',true));$fallback=gmr_theme_artist_image_id($term);$portrait=$portrait?:$fallback;$cover=$cover?:$fallback;$bio=get_term_meta($term->term_id,'gmr_artist_biography',true);$history=get_term_meta($term->term_id,'gmr_artist_history',true);$chronology=get_term_meta($term->term_id,'gmr_artist_chronology',true);$awards=get_term_meta($term->term_id,'gmr_artist_awards',true);$media_ids=array_filter(array_map('absint',explode(',',get_term_meta($term->term_id,'gmr_artist_media_ids',true))));global$wp_query;$work_count=(int)$wp_query->found_posts;
?>
<section class="gmr-artist-hero"><div class="gmr-artist-hero__cover"><?php echo $cover?wp_get_attachment_image($cover,'full'):'';?></div><div class="gmr-artist-hero__shade"></div><div class="gmr-wrap gmr-artist-hero__content"><div><span class="gmr-kicker">Artista · Galería Mayarí Rojas</span><h1><?php echo esc_html($term->name);?></h1><p><?php echo esc_html($term->description?:wp_trim_words(wp_strip_all_tags($bio),24));?></p><a class="gmr-button" href="#obra">Ver obra en la galería</a></div><?php if($portrait):?><figure><?php echo wp_get_attachment_image($portrait,'large');?></figure><?php endif;?></div></section>
<?php if($bio):?><section class="gmr-section gmr-artist-bio"><div class="gmr-wrap gmr-artist-editorial"><div><span class="gmr-kicker">Biografía</span><h2>Una mirada a su vida y obra.</h2></div><div class="gmr-editorial"><?php echo wp_kses_post(wpautop($bio));?></div></div></section><?php endif;?>
<?php if($history):?><section class="gmr-section gmr-artist-history"><div class="gmr-wrap gmr-artist-editorial"><div><span class="gmr-kicker">Trayectoria</span><h2>Historia artística</h2></div><div class="gmr-editorial"><?php echo wp_kses_post(wpautop($history));?></div></div></section><?php endif;?>
<?php if($chronology):?><section class="gmr-section gmr-artist-chronology"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">Cronología</span><h2>Etapas y momentos</h2></div></div><div class="gmr-timeline"><?php echo wp_kses_post($chronology);?></div></div></section><?php endif;?>
<section class="gmr-section gmr-artist-works" id="obra"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker"><?php echo esc_html($work_count.' '.(1===$work_count?'obra visible':'obras visibles'));?></span><h2>Obra en la galería</h2></div><a class="gmr-home-line-link" href="<?php echo esc_url(add_query_arg('artista',$term->slug,get_post_type_archive_link('product')));?>">Ver en catálogo</a></div><?php if(have_posts()):?><div class="gmr-grid"><?php while(have_posts()){the_post();get_template_part('template-parts/artwork','card');}?></div><nav class="gmr-pagination"><?php the_posts_pagination();?></nav><?php else:?><p class="gmr-empty">No hay obras visibles de este artista.</p><?php endif;?></div></section>
<?php if($awards||$media_ids):?><section class="gmr-section gmr-artist-archive"><div class="gmr-wrap"><div class="gmr-section__head"><div><span class="gmr-kicker">Archivo</span><h2>Reconocimientos y memoria</h2></div></div><?php if($awards):?><div class="gmr-editorial gmr-artist-awards"><?php echo wp_kses_post(wpautop($awards));?></div><?php endif;?><?php if($media_ids):?><div class="gmr-artist-media"><?php foreach($media_ids as$image_id)echo wp_get_attachment_image($image_id,'large');?></div><?php endif;?></div></section><?php endif;?>
<?php get_footer();?>
